Repository e-m-b-a/emba, pull requests merged in 2021-12, with the labels that each got.

#190 respect older kernel modules
  modules/S25_kernel_check.sh
Labels: bug, enhancement

#188 Net change
  helpers/helpers_emba_dependency_check.sh
  installer.sh
Labels: bug, docker

#191 little fixes
  config/bin_version_strings.cfg
  installer.sh
  modules/P25_kernel_bin_identifier.sh
  modules/S25_kernel_check.sh
  scan-profiles/default-scan.emba
Labels: bug, enhancement

#192 Add license links to webreport
  config/bin_version_strings_links.cfg
  helpers/helpers_emba_html_generator.sh
Labels: enhancement

#195 moved to csv configuration, bugs, versions
  config/bin_version_strings.cfg
  config/bin_version_strings_links.cfg
  emba.sh
  helpers/helpers_emba_dependency_check.sh
  helpers/helpers_emba_helpers.sh
  helpers/helpers_emba_prepare.sh
  helpers/helpers_emba_print.sh
  modules/F05_qemu_version_detection.sh
  modules/F19_cve_aggregator.sh
  modules/P02_firmware_bin_file_check.sh
  modules/P20_firmware_bin_extractor.sh
  modules/P25_kernel_bin_identifier.sh
  modules/P70_firmware_bin_base_analyzer.sh
  modules/S09_firmware_base_version_check.sh
  modules/S13_weak_func_check.sh
  modules/S14_weak_func_radare_check.sh
Labels: bug, enhancement

#196 Embark logo now in webreport
  config/bin_version_strings_links.cfg
  helpers/base.html
  helpers/embark.svg
  helpers/helpers_emba_html_generator.sh
  helpers/style.css
Labels: enhancement, EMBArk, web-reporter

#197 log4j detection, move to csv
  config/bin_version_strings.cfg
  config/bin_version_strings_links.cfg
  helpers/helpers_emba_dependency_check.sh
  helpers/helpers_emba_prepare.sh
  installer.sh
  modules/F05_qemu_version_detection.sh
  modules/F19_cve_aggregator.sh
  modules/F20_vul_aggregator.sh
  modules/F50_base_aggregator.sh
  modules/L10_system_emulator.sh
  modules/L15_emulated_checks_init.sh
  modules/S06_distribution_identification.sh
  modules/S09_firmware_base_version_check.sh
  modules/S116_qemu_version_detection.sh
  modules/S13_weak_func_check.sh
  modules/S14_weak_func_radare_check.sh
  modules/S24_kernel_bin_identifier.sh
  modules/S25_kernel_check.sh
Labels: bug, enhancement, Installation

#199 UBI extractor
  config/bin_version_strings.cfg
  helpers/helpers_emba_dependency_check.sh
  installer.sh
  modules/P02_firmware_bin_file_check.sh
  modules/P15_ubi_extractor.sh
Labels: enhancement

#200 little fix
  helpers/helpers_emba_dependency_check.sh
Labels: bug

#201 Improved the deep extraction mode
  config/bin_version_strings.cfg
  modules/P02_firmware_bin_file_check.sh
  modules/P10_vmdk_extractor.sh
  modules/P11_dlink_SHRS_enc_extract.sh
  modules/P12_avm_freetz_ng_extract.sh
  modules/P14_ext2_mounter.sh
  modules/P15_ubi_extractor.sh
  modules/P20_firmware_bin_extractor.sh
Labels: enhancement

#202 Little fixes are around
  modules/F50_base_aggregator.sh
  modules/S06_distribution_identification.sh
  modules/S25_kernel_check.sh
Labels: bug

#204 EnGenius extractor
  config/msf_cve-db.txt
  helpers/helpers_emba_dependency_check.sh
  installer.sh
  modules/P02_firmware_bin_file_check.sh
  modules/P16_EnGenius_decryptor.sh
  modules/P20_firmware_bin_extractor.sh
  modules/P99_prepare_analyzer.sh
  modules/S115_usermode_emulator.sh
  modules/S116_qemu_version_detection.sh
  modules/S14_weak_func_radare_check.sh
Labels: bug, enhancement

#205 Include networking details in final f50
  config/bin_version_strings.cfg
  emba.sh
  helpers/helpers_emba_dependency_check.sh
  modules/F20_vul_aggregator.sh
  modules/F50_base_aggregator.sh
  modules/P20_firmware_bin_extractor.sh
  modules/S25_kernel_check.sh
Labels: enhancement
