Repository e-m-b-a/emba, pull requests merged in 2021-05, with the labels that each got.

#105 wget identifier, disable core dumps and threading updates
  config/bin_version_strings.cfg
  modules/F19_cve_aggregator.sh
  modules/S110_yara_check.sh
  modules/S115_usermode_emulator.sh
  modules/S20_shell_check.sh
  modules/S21_python_check.sh
  modules/S22_php_check.sh
  modules/S25_kernel_check.sh
  modules/S95_interesting_binaries_check.sh
Labels: enhancement

#107 Updated deep extraction and s110
  emba.sh
  helpers/helpers.sh
  helpers/prepare.sh
  helpers/print.sh
  modules/F19_cve_aggregator.sh
  modules/F50_base_aggregator.sh
  modules/P05_firmware_bin_extractor.sh
  modules/P07_firmware_bin_base_analyzer.sh
  modules/S09_firmware_base_version_check.sh
  modules/S110_yara_check.sh
  modules/S115_usermode_emulator.sh
Labels: bug, enhancement

#108 Fix deep search
  modules/S103_deep_search.sh
Labels: bug

#109 bug in P07
  modules/P07_firmware_bin_base_analyzer.sh
Labels: bug

#110 S10 split, S108 removed, P07 cleaned
  helpers/dependency_check.sh
  installer.sh
  modules/F50_base_aggregator.sh
  modules/P02_firmware_bin_file_check.sh
  modules/P07_firmware_bin_base_analyzer.sh
  modules/S05_firmware_details.sh
  modules/S108_linux_common_file_checker.sh
  modules/S10_binaries_basic_check.sh
  modules/S10_binaries_check.sh
  modules/S11_weak_func_check.sh
  modules/S12_binary_protection.sh
Labels: enhancement

#101 Rewrite web report
  .github/workflows/main.yml
  emba.sh
  helpers/base.html
  helpers/dependency_check.sh
  helpers/helpers.sh
  helpers/html_converter.sh
  helpers/html_generator.sh
  helpers/style.css
  installer.sh
  modules/F19_cve_aggregator.sh
  modules/S105_deep_key_search.sh
  modules/S25_kernel_check.sh
  modules/S30_version_vulnerability_check.sh
Labels: enhancement

#112 F19 and S115 updates, cleanups, certificate details
  emba.sh
  helpers/helpers.sh
  helpers/prepare.sh
  modules/F19_cve_aggregator.sh
  modules/P02_firmware_bin_file_check.sh
  modules/S09_firmware_base_version_check.sh
  modules/S103_deep_search.sh
  modules/S10_binaries_basic_check.sh
  modules/S115_usermode_emulator.sh
  modules/S11_weak_func_check.sh
  modules/S60_cert_file_check.sh
Labels: enhancement

#113 firmware size warning
  emba.sh
  helpers/prepare.sh
Labels: enhancement
