Repository e-m-b-a/emba, pull requests merged in 2021-06, with the labels that each got.

#116 CSV aggregator
  modules/F50_base_aggregator.sh
Labels: enhancement

#120 Scan profile support
  emba.sh
  helpers/print.sh
  modules/F50_base_aggregator.sh
  scan-profiles/default-scan-docker.emba
  scan-profiles/default-scan.emba
  scan-profiles/full-scan-docker.emba
  scan-profiles/full-scan.emba
Labels: enhancement

#121 Webreport updates
  emba.sh
  helpers/base.html
  helpers/dependency_check.sh
  helpers/helpers.sh
  helpers/html_generator.sh
  helpers/path.sh
  helpers/print.sh
  helpers/style.css
  installer.sh
  modules/F19_cve_aggregator.sh
  modules/F50_base_aggregator.sh
  modules/P02_firmware_bin_file_check.sh
  modules/S05_firmware_details.sh
  modules/S103_deep_search.sh
  modules/S106_deep_key_search.sh
  modules/S110_yara_check.sh
  modules/S115_usermode_emulator.sh
  modules/S11_weak_func_check.sh
  modules/S120_cwe_checker.sh
  modules/S15_bootloader_check.sh
  modules/S20_shell_check.sh
  modules/S21_python_check.sh
  modules/S22_php_check.sh
  modules/S25_kernel_check.sh
  modules/S30_version_vulnerability_check.sh
  modules/S40_weak_perm_check.sh
  modules/S45_pass_file_check.sh
  modules/S50_authentication_check.sh
  modules/S55_history_file_check.sh
  modules/S60_cert_file_check.sh
  modules/S85_ssh_check.sh
  modules/S95_interesting_binaries_check.sh
Labels: bug, enhancement

#123 some little fixes
  helpers/helpers.sh
  installer.sh
  modules/F19_cve_aggregator.sh
Labels: bug

#127 New RTOS handling
  config/bin_version_strings.cfg
  config/msf_cve-db.txt
  emba.sh
  helpers/html_generator.sh
  helpers/prepare.sh
  helpers/print.sh
  modules/F19_cve_aggregator.sh
  modules/F50_base_aggregator.sh
  modules/P07_firmware_bin_base_analyzer.sh
  modules/R09_firmware_base_version_check.sh
  modules/S05_firmware_details.sh
  modules/S09_firmware_base_version_check.sh
  modules/S106_deep_key_search.sh
  modules/S115_usermode_emulator.sh
  modules/S11_weak_func_check.sh
  modules/S120_cwe_checker.sh
  modules/S25_kernel_check.sh
  scan-profiles/default-scan-docker-no-web.emba
Labels: bug, enhancement

#130 little output cleanup
  modules/F50_base_aggregator.sh
  modules/S120_cwe_checker.sh
Labels: enhancement
