Repository e-m-b-a/emba, pull requests merged in 2021-07, with the labels that each got.

#134 Virustotal and hash searcher module
  .gitignore
  config/bin_version_strings.cfg
  config/msf_cve-db.txt
  config/password_regex.cfg
  emba.sh
  helpers/print.sh
  modules/F19_cve_aggregator.sh
  modules/F50_base_aggregator.sh
  modules/P02_firmware_bin_file_check.sh
  modules/P03_firmware_virustotal_check.sh
  modules/P05_firmware_bin_extractor.sh
  modules/P07_firmware_bin_base_analyzer.sh
  modules/S05_firmware_details.sh
  modules/S09_firmware_base_version_check.sh
  modules/S107_deep_password_search.sh
  modules/S115_usermode_emulator.sh
  modules/S45_pass_file_check.sh
Labels: bug, enhancement

#135 linking cert details
  modules/S60_cert_file_check.sh
Labels: enhancement

#136 Fix sed again
  helpers/html_generator.sh
  helpers/path.sh
  helpers/prepare.sh
  helpers/print.sh
  modules/F19_cve_aggregator.sh
  modules/F50_base_aggregator.sh
  modules/P05_firmware_bin_extractor.sh
  modules/S05_firmware_details.sh
  modules/S09_firmware_base_version_check.sh
  modules/S110_yara_check.sh
  modules/S115_usermode_emulator.sh
  modules/S11_weak_func_check.sh
Labels: bug

#138 Version updates
  config/bin_version_strings.cfg
Labels: enhancement

#139 64bit emulation - init, bug fixing
  config/msf_cve-db.txt
  config/password_regex.cfg
  modules/F19_cve_aggregator.sh
  modules/S115_usermode_emulator.sh
Labels: enhancement

#140 apk extraction mode
  config/bin_version_strings.cfg
  modules/F19_cve_aggregator.sh
  modules/P05_firmware_bin_extractor.sh
  modules/S85_ssh_check.sh
Labels: enhancement
