Repository e-m-b-a/emba, pull requests merged in 2021-09, with the labels that each got.

#154 Install cwe_checker locally
  installer.sh
  modules/S120_cwe_checker.sh
Labels: enhancement

#152 Docker mode, installer updates
  .dockerignore
  Dockerfile
  README.md
  check_project.sh
  config/bin_version_strings.cfg
  config/msf_cve-db.txt
  docker-compose.yml
  emba.sh
  helpers/dependency_check.sh
  helpers/print.sh
  installer.sh
  modules/F19_cve_aggregator.sh
  modules/F50_base_aggregator.sh
  modules/P20_firmware_bin_extractor.sh
  modules/P70_firmware_bin_base_analyzer.sh
  modules/S115_usermode_emulator.sh
  scan-profiles/default-scan-docker-no-web.emba
  scan-profiles/default-scan-docker.emba
  scan-profiles/default-scan.emba
  scan-profiles/full-scan-docker.emba
  scan-profiles/full-scan.emba
Labels: bug, enhancement, docker

#157 add install instructions to README, installer cosmetics
  README.md
  config/cve_database_updater.init
  config/emba_updater.init
  config/msf_cve-db.txt
  helpers/base.html
  helpers/dependency_check.sh
  helpers/helpers.sh
  helpers/print.sh
  installer.sh
  modules/S120_cwe_checker.sh
Labels: bug, documentation, enhancement

#158 removed documentation folders
  documentation/emba-kernel_check.png
  documentation/emba_01.png
  documentation/emba_02.png
  documentation/emba_03.png
  documentation/emba_04.png
  documentation/emba_05.png
  documentation/emba_06.png
  documentation/emba_07.png
  documentation/emba_binwalker.png
  documentation/emba_cve_exploits.png
  documentation/emba_detected_CVEs.png
  documentation/emba_emulator-busybox.png
  documentation/emba_emulator-results.png
  documentation/emba_reporter.png
  documentation/emba_static_version_detection.png
  documentation/report_usage.jpg
  documentation/top10-strcpy.png
Labels: documentation

#160 Webui updates and sorting msf db
  config/msf_cve-db.txt
  helpers/base.html
  helpers/favicon.png
  helpers/html_generator.sh
  helpers/prepare.sh
  helpers/style.css
  modules/S120_cwe_checker.sh
Labels: bug, enhancement

#161 strcpy and system results with binary protection
  modules/F50_base_aggregator.sh
Labels: enhancement

#163 Kali 2021-03 updates
  config/msf_cve-db.txt
  modules/P20_firmware_bin_extractor.sh
Labels: enhancement

#166 s7-400 detection
  config/bin_version_strings.cfg
  modules/F19_cve_aggregator.sh
  modules/F50_base_aggregator.sh
  modules/P20_firmware_bin_extractor.sh
  modules/P70_firmware_bin_base_analyzer.sh
Labels: enhancement

#165 Include endianness in architecture detection
  helpers/prepare.sh
  modules/F50_base_aggregator.sh
Labels: enhancement
