Repository e-m-b-a/emba, pull requests merged in 2021-03, with the labels that each got.

#58 improve extractor, new logs
  config/bin_version_strings.cfg
  modules/F19_cve_aggregator.sh
  modules/P05_firmware_bin_extractor.sh
  modules/P07_firmware_bin_base_analyzer.sh
  modules/P09_firmware_base_version_check.sh
  modules/S115_usermode_emulator.sh
Labels: enhancement

#62 Speedup emba
  config/bin_version_strings.cfg
  config/cert_files.cfg
  emba.sh
  helpers/dependency_check.sh
  helpers/path.sh
  helpers/prepare.sh
  helpers/print.sh
  modules/F19_cve_aggregator.sh
  modules/F50_base_aggregator.sh
  modules/P02_firmware_bin_file_check.sh
  modules/P05_firmware_bin_extractor.sh
  modules/P07_firmware_bin_base_analyzer.sh
  modules/R09_firmware_base_version_check.sh
  modules/S05_firmware_details.sh
  modules/S09_firmware_base_version_check.sh
  modules/S100_command_inj_check.sh
  modules/S103_deep_search.sh
  modules/S105_deep_key_search.sh
  modules/S108_linux_common_file_checker.sh
  modules/S10_binaries_check.sh
  modules/S110_yara_check.sh
  modules/S115_usermode_emulator.sh
  modules/S120_cwe_checker.sh
  modules/S15_bootloader_check.sh
  modules/S20_shell_check.sh
  modules/S21_python_check.sh
  modules/S22_php_check.sh
  modules/S25_kernel_check.sh
  modules/S30_version_vulnerability_check.sh
  modules/S35_http_file_check.sh
  modules/S40_weak_perm_check.sh
  modules/S45_pass_file_check.sh
  modules/S50_authentication_check.sh
  modules/S55_history_file_check.sh
  modules/S60_cert_file_check.sh
  modules/S65_config_file_check.sh
  modules/S70_hidden_file_check.sh
  modules/S75_network_check.sh
  modules/S80_cronjob_check.sh
  modules/S85_ssh_check.sh
  modules/S90_mail_check.sh
  modules/S95_interesting_binaries_check.sh
Labels: enhancement

#63 Improve verified VxWorks detection
  config/bin_version_strings.cfg
  modules/F19_cve_aggregator.sh
  modules/F50_base_aggregator.sh
  modules/P07_firmware_bin_base_analyzer.sh
  modules/R09_firmware_base_version_check.sh
Labels: enhancement

#67 Installer cve search database
  installer.sh
Labels: enhancement

#71 Revert "Update emba.sh"
  docker-compose.yml
  emba.sh
  installer.sh
Labels: docker, enhancement

#72 fixed root filesystme detection
  helpers/prepare.sh
Labels: bug

#74 fix cwe checker
  modules/S120_cwe_checker.sh
Labels: bug

#75 Much cleaner OS detection
  config/bin_version_strings.cfg
  config/emulation_blacklist.cfg
  modules/F19_cve_aggregator.sh
  modules/F50_base_aggregator.sh
Labels: enhancement

#79 Fix the protection of filling up the disk
  modules/F19_cve_aggregator.sh
  modules/P05_firmware_bin_extractor.sh
  modules/S10_binaries_check.sh
Labels: bug

#81 fix process killing on exhausting disk space
  config/bin_version_strings.cfg
  modules/F19_cve_aggregator.sh
  modules/P05_firmware_bin_extractor.sh
Labels: bug

#82 Sudoers check
  helpers/dependency_check.sh
  installer.sh
  modules/S50_authentication_check.sh
Labels: enhancement

#83 Sshd config checker
  helpers/dependency_check.sh
  installer.sh
  modules/S85_ssh_check.sh
Labels: enhancement

#84 make kernel search unique
  modules/S25_kernel_check.sh
Labels: enhancement

#78 Fix -s switch
  emba.sh
  helpers/path.sh
  modules/P05_firmware_bin_extractor.sh
  modules/P07_firmware_bin_base_analyzer.sh
Labels: bug

#86 Sudo parser updates
  config/sudoers_files.cfg
  modules/S115_usermode_emulator.sh
  modules/S50_authentication_check.sh
Labels: bug, enhancement
