Repository e-m-b-a/emba, pull requests merged in 2022-03, with the labels that each got.

#225 fix trickest install
  installer/IF20_cve_search.sh
  installer/IF50_aggregator_common.sh
Labels: bug, Installation

#227 Restructure S06 and improve rootfs detection
  config/distri_id.cfg
  emba.sh
  helpers/helpers_emba_prepare.sh
  modules/F20_vul_aggregator.sh
  modules/P05_fact_init.sh
  modules/P10_vmdk_extractor.sh
  modules/P14_ext2_mounter.sh
  modules/P15_ubi_extractor.sh
  modules/P18_qnap_decryptor.sh
  modules/P19_bsd_ufs_mounter.sh
  modules/S06_distribution_identification.sh
  modules/S09_firmware_base_version_check.sh
Labels: enhancement

#226 DLink-X-decryption
  config/report_templates/P11_dlink_SHRS_enc_extract-post.sh
  modules/P11_dlink_SHRS_enc_extract.sh
  modules/P60_firmware_bin_extractor.sh
Labels: enhancement

#229 Small cleanup
  config/bin_version_strings.cfg
  config/report_templates/S03_firmware_bin_base_analyzer-pre.sh
  config/report_templates/S06_distribution_identification-pre.sh
  config/report_templates/S10_binaries_basic_check-pre.sh
  config/report_templates/S20_shell_check-pre.sh
  config/report_templates/S24_kernel_bin_identifier-pre.sh
  config/report_templates/S25_kernel_check-pre.sh
  config/report_templates/S35_http_file_check-pre.sh
  config/report_templates/S45_pass_file_check-pre.sh
  config/report_templates/S60_cert_file_check-pre.sh
  config/report_templates/S65_config_file_check-pre.sh
  config/report_templates/S70_hidden_file_check-pre.sh
  config/report_templates/S85_ssh_check-pre.sh
  docker-compose.yml
  helpers/helpers_emba_dependency_check.sh
  helpers/helpers_emba_prepare.sh
  modules/F20_vul_aggregator.sh
  modules/F50_base_aggregator.sh
  modules/S03_firmware_bin_base_analyzer.sh
  modules/S115_usermode_emulator.sh
  modules/S65_config_file_check.sh
Labels: bug, enhancement
