Repository e-m-b-a/emba, pull requests merged in 2022-11, with the labels that each got.

#381 lzo - ubi extractor fix
  installer/I24_25_kernel_tools.sh
Labels: bug

#380 Prepare support for further architectures
  config/msf_cve-db.txt
  docker-compose.yml
  emba.sh
  helpers/helpers_emba_dependency_check.sh
  helpers/helpers_emba_helpers.sh
  helpers/helpers_emba_prepare.sh
  installer.sh
  installer/I01_default_apps.sh
  installer/I02_UEFI_fwhunt.sh
  installer/I120_cwe_checker.sh
  installer/I199_default_tools_github.sh
  installer/I24_25_kernel_tools.sh
  installer/IF20_cve_search.sh
  installer/IL15_emulated_checks_init.sh
  installer/IP00_extractors.sh
  installer/IP61_unblob.sh
  installer/IP99_binwalk_default.sh
  modules/F50_base_aggregator.sh
  modules/L10_system_emulation.sh
  modules/P15_ubi_extractor.sh
  modules/P22_Zyxel_zip_decrypt.sh
  modules/P61_unblob_eval.sh
  modules/S115_usermode_emulator.sh
  modules/S120_cwe_checker.sh
  modules/S13_weak_func_check.sh
  modules/S14_weak_func_radare_check.sh
  modules/S20_shell_check.sh
  modules/S22_php_check.sh
  modules/S24_kernel_bin_identifier.sh
  modules/S25_kernel_check.sh
Labels: bug, enhancement, System emulator (Lxx)

#384 typo
  installer/IF20_cve_search.sh
Labels: bug, Installation

#385 Check disk space for installation
  installer.sh
Labels: bug, enhancement, Installation

#397 installer - missed this
  installer.sh
Labels: bug, Installation

#399 Qualcom DSP6 - basic support
  helpers/helpers_emba_dependency_check.sh
  helpers/helpers_emba_prepare.sh
Labels: enhancement

#401 Installer fix
  installer.sh
Labels: bug, Installation

#398 nikto install fix
  helpers/helpers_emba_dependency_check.sh
  installer/IL15_emulated_checks_init.sh
Labels: bug, Installation

#374 Better UEFI extractor
  helpers/helpers_emba_dependency_check.sh
  installer.sh
  installer/IP35_uefi_extraction.sh
  installer/helpers.sh
  modules/F50_base_aggregator.sh
  modules/P35_UEFI_extractor.sh
Labels: enhancement, Extractor (Pxx)

#403 Make installer.sh executeable again
  installer.sh
Labels: bug, Installation

#402 ARM64 support
  Dockerfile
  docker-compose.yml
  helpers/helpers_emba_dependency_check.sh
  helpers/helpers_emba_prepare.sh
  installer/IL10_system_emulator.sh
  installer/IL15_emulated_checks_init.sh
  modules/F50_base_aggregator.sh
  modules/L10_system_emulation.sh
  modules/P23_qemu_qcow_mounter.sh
  modules/P35_UEFI_extractor.sh
Labels: bug, enhancement, Extractor (Pxx), System emulator (Lxx)

#408 Improve CSV export of s24
  helpers/helpers_emba_prepare.sh
  installer/I199_default_tools_github.sh
  installer/IF50_aggregator_common.sh
  modules/S24_kernel_bin_identifier.sh
Labels: enhancement, reporting, Core modules (Sxx)

#411 Trickest blacklist
  config/trickest_blacklist.txt
  helpers/helpers_emba_helpers.sh
  helpers/helpers_emba_prepare.sh
  installer/IF20_cve_search.sh
  installer/IF50_aggregator_common.sh
  installer/IL10_system_emulator.sh
  installer/IL15_emulated_checks_init.sh
Labels: enhancement, help wanted, issue in 3rd party component

#412 log color, init sort, web reporter
  config/banner/MSF_Edt-v1.1.3.txt
  config/bin_version_strings.cfg
  helpers/helpers_emba_html_generator.sh
  helpers/helpers_emba_print.sh
  modules/F50_base_aggregator.sh
  modules/L10_system_emulation.sh
  modules/L10_system_emulation/inferFile.sh
  modules/L30_routersploit.sh
  modules/P35_UEFI_extractor.sh
  modules/P61_unblob_eval.sh
  modules/S14_weak_func_radare_check.sh
  modules/S15_bootloader_check.sh
  modules/S20_shell_check.sh
Labels: bug

#414 User-mode emulator fixes
  config/bin_version_strings.cfg
  modules/S115_usermode_emulator.sh
  modules/S13_weak_func_check.sh
  modules/S14_weak_func_radare_check.sh
Labels: bug
