Repository e-m-b-a/emba, pull requests merged in 2022-01, with the labels that each got.

#206 GPG compression
  config/bin_version_strings.cfg
  modules/F50_base_aggregator.sh
  modules/P02_firmware_bin_file_check.sh
  modules/P17_gpg_decompress.sh
  modules/P20_firmware_bin_extractor.sh
  modules/S06_distribution_identification.sh
  modules/S12_binary_protection.sh
  modules/S13_weak_func_check.sh
  modules/S14_weak_func_radare_check.sh
Labels: enhancement

#207 STACS hash detection and Matrix mode
  config/bin_version_strings.cfg
  emba.sh
  helpers/helpers_emba_dependency_check.sh
  helpers/helpers_emba_print.sh
  installer.sh
  modules/S107_deep_password_search.sh
  modules/S108_stacs_password_search.sh
Labels: enhancement

#208 STACS update, little fixes
  config/bin_version_strings.cfg
  helpers/helpers_emba_dependency_check.sh
  modules/F20_vul_aggregator.sh
  modules/L10_system_emulator.sh
  modules/S108_stacs_password_search.sh
  modules/S115_usermode_emulator.sh
Labels: bug, enhancement

#203 make dependency-check failing
  helpers/helpers_emba_dependency_check.sh
Labels: bug

#209 recover interface address / QNAP extractor
  config/bin_version_strings.cfg
  emba.sh
  helpers/helpers_emba_dependency_check.sh
  installer.sh
  modules/F10_license_summary.sh
  modules/F20_vul_aggregator.sh
  modules/P02_firmware_bin_file_check.sh
  modules/P11_dlink_SHRS_enc_extract.sh
  modules/P16_EnGenius_decryptor.sh
  modules/P18_qnap_decryptor.sh
  modules/P20_firmware_bin_extractor.sh
  modules/S09_firmware_base_version_check.sh
  modules/S115_usermode_emulator.sh
Labels: bug, enhancement

#210 QNAP extractor, emulation improvements
  config/bin_version_strings.cfg
  config/deep_key_search.cfg
  config/msf_cve-db.txt
  emba.sh
  modules/P02_firmware_bin_file_check.sh
  modules/P11_dlink_SHRS_enc_extract.sh
  modules/P16_EnGenius_decryptor.sh
  modules/P17_gpg_decompress.sh
  modules/P18_qnap_decryptor.sh
  modules/P60_firmware_bin_extractor.sh
  modules/P70_firmware_bin_base_analyzer.sh
  modules/S09_firmware_base_version_check.sh
  modules/S115_usermode_emulator.sh
Labels: enhancement

#211 phpinfo detection
  modules/S22_php_check.sh
Labels: enhancement

#212 Update templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement
