Repository e-m-b-a/emba, pull requests merged in 2022-07, with the labels that each got.

#261 Fix links in web report and new parameters
  config/msf_cve-db.txt
  emba.sh
  helpers/helpers_emba_dependency_check.sh
  helpers/helpers_emba_html_generator.sh
  helpers/helpers_emba_prepare.sh
  helpers/helpers_emba_print.sh
Labels: bug, enhancement

#262 Foscam/Buffalo firmware decryption module / BigIP detection / Bug fixes
  .github/workflows/inactive_issues.yml
  CONTRIBUTING.md
  check_project.sh
  config/bin_version_strings.cfg
  config/distri_id.cfg
  config/foscam_enc_keys.txt
  config/msf_cve-db.txt
  config/report_templates/F20_vul_aggregator-post.sh
  docker-compose.yml
  emba.sh
  helpers/helpers_emba_dependency_check.sh
  helpers/helpers_emba_helpers.sh
  helpers/helpers_emba_html_generator.sh
  helpers/helpers_emba_prepare.sh
  helpers/helpers_emba_print.sh
  installer/I120_cwe_checker.sh
  installer/IP00_extractors.sh
  installer/IP12_avm_freetz_ng_extract.sh
  modules/F20_vul_aggregator.sh
  modules/P02_firmware_bin_file_check.sh
  modules/P20_foscam_decryptor.sh
  modules/P60_firmware_bin_extractor.sh
  modules/S06_distribution_identification.sh
  modules/S120_cwe_checker.sh
Labels: bug, enhancement

#266 Yara search path fix
  modules/S110_yara_check.sh
Labels: bug

#271 Threading, notifications, CVSSv3
  config/banner/Singapore_Edt-v1.0.0.txt
  config/banner/Vegas_Edt-v1.1.0.txt
  config/bin_version_strings.cfg
  config/report_templates/F20_vul_aggregator-pre.sh
  emba.sh
  helpers/helpers_emba_dependency_check.sh
  helpers/helpers_emba_helpers.sh
  helpers/helpers_emba_print.sh
  installer/I01_default_apps_host.sh
  modules/F20_vul_aggregator.sh
  modules/F50_base_aggregator.sh
  modules/P03_firmware_virustotal_check.sh
  modules/P05_patools_init.sh
  modules/P10_vmdk_extractor.sh
  modules/P11_dlink_SHRS_enc_extract.sh
  modules/P12_avm_freetz_ng_extract.sh
  modules/P13_uboot_mkimage.sh
  modules/P14_ext_mounter.sh
  modules/P15_ubi_extractor.sh
  modules/P16_EnGenius_decryptor.sh
  modules/P17_gpg_decompress.sh
  modules/P18_qnap_decryptor.sh
  modules/P19_bsd_ufs_mounter.sh
  modules/P20_foscam_decryptor.sh
  modules/P21_buffalo_decryptor.sh
  modules/P25_android_ota.sh
  modules/P60_firmware_bin_extractor.sh
  modules/S09_firmware_base_version_check.sh
  modules/S103_deep_search.sh
  modules/S106_deep_key_search.sh
  modules/S110_yara_check.sh
  modules/S115_usermode_emulator.sh
  modules/S120_cwe_checker.sh
  modules/S13_weak_func_check.sh
  modules/S14_weak_func_radare_check.sh
  modules/S20_shell_check.sh
  modules/S21_python_check.sh
  modules/S22_php_check.sh
  modules/S25_kernel_check.sh
  modules/S50_authentication_check.sh
  modules/S85_ssh_check.sh
  modules/S99_grepit.sh
  scan-profiles/default-scan-no-notify.emba
Labels: enhancement

#272 Status bar
  config/msf_cve-db.txt
  emba.sh
  helpers/helpers_emba_helpers.sh
  helpers/helpers_emba_print.sh
  helpers/helpers_emba_status_bar.sh
  modules/S115_usermode_emulator.sh
Labels: enhancement

#274 Experimental WSL support
  check_project.sh
  config/emba_updater.init
  config/msf_cve-db.txt
  emba.sh
  helpers/helpers_emba_dependency_check.sh
  helpers/helpers_emba_print.sh
  installer.sh
  installer/I05_emba_docker_image_dl.sh
  installer/ID1_ubuntu_os.sh
  installer/IF20_cve_search.sh
  modules/P03_firmware_virustotal_check.sh
  modules/S09_firmware_base_version_check.sh
  modules/S115_usermode_emulator.sh
  modules/S13_weak_func_check.sh
  modules/S14_weak_func_radare_check.sh
  modules/S60_cert_file_check.sh
Labels: Installation

#279 Ubuntu-recommendations
  emba.sh
  helpers/helpers_emba_dependency_check.sh
Labels: web-reporter

#277 Setup status bar option
  emba.sh
  helpers/helpers_emba_print.sh
  helpers/helpers_emba_status_bar.sh
Labels: enhancement

#281 Speed improvements for module s106 and s110
  emba.sh
  helpers/helpers_emba_print.sh
  installer/I120_cwe_checker.sh
  modules/S09_firmware_base_version_check.sh
  modules/S106_deep_key_search.sh
  modules/S110_yara_check.sh
  modules/S14_weak_func_radare_check.sh
Labels: enhancement
