Repository e-m-b-a/emba, pull requests merged in 2023-05, with the labels that each got.

#608 R2 decompiler integration
  .github/workflows/trickest_update.yml
  config/functions.cfg
  emba
  helpers/helpers_emba_dependency_check.sh
  helpers/trickest_db_update.sh
  installer.sh
  installer/I108_stacs_password_search.sh
  installer/I13_disasm.sh
  installer/IL15_emulated_checks_init.sh
  modules/S07_bootloader_check.sh
  modules/S108_stacs_password_search.sh
  modules/S13_weak_func_check.sh
  modules/S14_weak_func_radare_check.sh
  modules/S15_radare_decompile_checks.sh
Labels: enhancement, Core modules (Sxx)

#609 url update for sasquatch deb
  installer/IP61_unblob.sh
Labels: enhancement, Extractor (Pxx)

#610 update ubuntu libssl source
  installer/ID1_ubuntu_os.sh
Labels: Installation, Ubuntu, WSL, issue in 3rd party component

#636 Fix all the things
  helpers/helpers_emba_html_generator.sh
  helpers/helpers_emba_system_emulation.sh
  modules/F50_base_aggregator.sh
  modules/L10_system_emulation.sh
  modules/L10_system_emulation/inferService.sh
  modules/L22_upnp_hnap_checks.sh
  modules/L25_web_checks.sh
  modules/P65_package_extractor.sh
  modules/S22_php_check.sh
  modules/S24_kernel_bin_identifier.sh
Labels: bug

#646 Routersploit/emulation cleanup/installer
  helpers/helpers_emba_dependency_check.sh
  helpers/helpers_emba_system_emulation.sh
  installer/IL15_emulated_checks_init.sh
  installer/IP61_unblob.sh
  installer/IP99_binwalk_default.sh
  modules/L10_system_emulation.sh
  modules/L30_routersploit.sh
Labels: bug
