Repository e-m-b-a/emba, pull requests merged in 2023-04, with the labels that each got.

#557 Improve web crawler (L25)
  installer.sh
  modules/L25_web_checks.sh
Labels: bug, System emulator (Lxx)

#565 SNMP module improvements
  README.md
  config/trickest_blacklist.txt
  modules/L20_snmp_checks.sh
  modules/L25_web_checks.sh
Labels: enhancement, System emulator (Lxx)

#564 Remove warning apt-key is deprecated
  installer/IF20_cve_search.sh
Labels: enhancement, Installation

#569 Ignore files containing the following paths: */dev/* */proc/* */sys/*
  modules/S115_usermode_emulator.sh
Labels: bug

#567 Fix arch detection in f50
  modules/F50_base_aggregator.sh
Labels: bug, Extractor (Pxx)

#570 Install fixes
  helpers/helpers_emba_dependency_check.sh
  installer/I108_stacs_password_search.sh
  installer/IP99_binwalk_default.sh
Labels: bug, Installation, Extractor (Pxx), issue in 3rd party component

#571 fix l10 error case
  modules/L10_system_emulation.sh
Labels: bug, System emulator (Lxx)

#579 Fail fetch aspnetcore-targeting-pack when cleaning up
  .github/workflows/default_install.yml
Labels: ci/cd

#580 fix actions, fix l10 lnk fixer
  .github/workflows/docker-image.yml
  .github/workflows/trivy-container-check.yml
  modules/L10_system_emulation.sh
  modules/P02_firmware_bin_file_check.sh
Labels: bug, System emulator (Lxx), ci/cd

#586 remove unneeded resource
  installer/IF20_cve_search.sh
Labels: bug

#589 SBOM generation fix for non vuln components
  helpers/helpers_emba_system_emulation.sh
  installer/I199_default_tools_github.sh
  modules/F20_vul_aggregator.sh
  modules/F50_base_aggregator.sh
  modules/L10_system_emulation/inferService.sh
  modules/S100_command_inj_check.sh
Labels: bug

#591 Lua script analysis support, UPnP live module, improvements
  installer/I20_sourcecode_check.sh
  installer/IL15_emulated_checks_init.sh
  modules/L10_system_emulation.sh
  modules/L10_system_emulation/inferService.sh
  modules/L22_upnp_checks.sh
  modules/L25_web_checks.sh
  modules/S23_lua_check.sh
Labels: enhancement, System emulator (Lxx), Core modules (Sxx)

#598 R.I.P. binwalk
  README.md
  config/banner/RIP-binwalk-v1.2.3.txt
  config/trickest_blacklist.txt
  helpers/helpers_emba_defaults.sh
  helpers/helpers_emba_dependency_check.sh
  helpers/helpers_emba_prepare.sh
  modules/L10_system_emulation.sh
  modules/L22_upnp_checks.sh
  modules/P02_firmware_bin_file_check.sh
  modules/P05_patools_init.sh
  modules/P11_dlink_SHRS_enc_extract.sh
  modules/P12_avm_freetz_ng_extract.sh
  modules/P13_uboot_mkimage.sh
  modules/P16_EnGenius_decryptor.sh
  modules/P17_gpg_decompress.sh
  modules/P18_qnap_decryptor.sh
  modules/P21_buffalo_decryptor.sh
  modules/P22_Zyxel_zip_decrypt.sh
  modules/P23_qemu_qcow_mounter.sh
  modules/P55_unblob_extractor.sh
  modules/P59_binwalk_extractor.sh
  modules/P60_deep_extractor.sh
  modules/P99_prepare_analyzer.sh
  modules/S23_lua_check.sh
Labels: enhancement, Extractor (Pxx), issue in 3rd party component

#601 ignore named pipe
  modules/S115_usermode_emulator.sh
Labels: bug

#603 apk extraction fix
  modules/P02_firmware_bin_file_check.sh
  modules/P65_package_extractor.sh
Labels: bug, Extractor (Pxx)
