Repository e-m-b-a/emba, pull requests merged in 2023-07, with the labels that each got.

#683 Little cleanups
  .github/workflows/trivy-container-check.yml
  config/bin_version_strings.cfg
  modules/L22_upnp_hnap_checks.sh
Labels: bug

#687 typo, csv cleanup
  helpers/helpers_emba_defaults.sh
  modules/L15_emulated_checks_nmap.sh
  modules/L25_web_checks.sh
Labels: bug

#695 Fix L15 report
  .github/trivy-container-check.yml.bak
  modules/L15_emulated_checks_nmap.sh
Labels: bug

#696 Improve web crawler
  helpers/helpers_emba_dependency_check.sh
  modules/L25_web_checks.sh
  modules/P02_firmware_bin_file_check.sh
  modules/P59_binwalk_extractor.sh
Labels: enhancement, System emulator (Lxx)

#698 Bug fixes
  config/bin_version_strings.cfg
  docker-compose.yml
  modules/P02_firmware_bin_file_check.sh
  modules/P59_binwalk_extractor.sh
  modules/S23_lua_check.sh
Labels: bug

#704 make qnap check strict mode compatible
  config/trickest_blacklist.txt
  modules/P02_firmware_bin_file_check.sh
Labels: bug

#707 Move to pip env for python installation
  emba
  helpers/helpers_emba_dependency_check.sh
  installer.sh
  installer/I02_UEFI_fwhunt.sh
  installer/IP61_unblob.sh
  installer/IP99_binwalk_default.sh
  installer/helpers.sh
  modules/P55_unblob_extractor.sh
Labels: enhancement, docker, Installation

#710 Sh eval checks
  modules/S20_shell_check.sh
Labels: enhancement, Core modules (Sxx)

#602 EMBA ChatGPT integration
  .gitignore
  check_project.sh
  config/gpt_config.env.template
  config/gpt_template.json
  docker-compose.yml
  emba
  helpers/helpers_emba_defaults.sh
  helpers/helpers_emba_dependency_check.sh
  helpers/helpers_emba_helpers.sh
  helpers/helpers_emba_html_generator.sh
  helpers/helpers_emba_internet_access.sh
  helpers/helpers_emba_print.sh
  helpers/style.css
  modules/F05_qs_resolver.sh
  modules/F50_base_aggregator.sh
  modules/Q02_openai_question.sh
  modules/S15_radare_decompile_checks.sh
  modules/S20_shell_check.sh
  modules/S21_python_check.sh
  modules/S22_php_check.sh
  modules/S23_lua_check.sh
  scan-profiles/default-scan-gpt.emba
Labels: enhancement, docker, reporting, in progress

#717 GPT rating improvements
  README.md
  helpers/helpers_emba_defaults.sh
  helpers/helpers_emba_print.sh
  modules/F05_qs_resolver.sh
  modules/F50_base_aggregator.sh
  modules/Q02_openai_question.sh
  modules/S15_radare_decompile_checks.sh
  modules/S20_shell_check.sh
  modules/S21_python_check.sh
  modules/S22_php_check.sh
  modules/S23_lua_check.sh
Labels: AI-assissted firmware analysis

#719 Release 1.3.0
  config/banner/AI-v1.3.0.txt
  config/banner/Blue_Hat-v1.2.2.txt
  config/banner/RIP-binwalk-v1.2.3.txt
  helpers/helpers_emba_defaults.sh
  modules/F05_qs_resolver.sh
  modules/Q02_openai_question.sh
Labels: enhancement, in progress, AI-assissted firmware analysis

#722 Internet check not blocking
  helpers/helpers_emba_dependency_check.sh
Labels: bug

#723 Fix docker build workflow
  .github/workflows/docker-image.yml
  docker-compose.yml
Labels: bug, docker, ci/cd
