Repository e-m-b-a/emba, pull requests merged in 2023-08, with the labels that each got.

#732 print fix, http crawler
  helpers/helpers_emba_internet_access.sh
  modules/L25_web_checks.sh
Labels: bug

#749 Fix updater
  config/emba_updater.init
  config/emba_updater_data.init
Labels: bug

#750 Unblob v23.8.11
  helpers/helpers_emba_dependency_check.sh
  installer.sh
  installer/I02_UEFI_fwhunt.sh
  installer/IP61_unblob.sh
  modules/P55_unblob_extractor.sh
Labels: enhancement

#736 PEM file with multiple certificates
  modules/F50_base_aggregator.sh
  modules/S60_cert_file_check.sh
Labels: bug, Core modules (Sxx)
