Repository e-m-b-a/emba, pull requests merged in 2023-06, with the labels that each got.

#647 zombie handling
  helpers/helpers_emba_helpers.sh
  helpers/helpers_emba_print.sh
  installer/I120_cwe_checker.sh
  modules/S120_cwe_checker.sh
Labels: bug

#654 JNAP detection
  .github/ISSUE_TEMPLATE/new_kali_release.md
  installer/IP61_unblob.sh
  modules/L10_system_emulation.sh
  modules/L15_emulated_checks_nmap.sh
  modules/L22_upnp_hnap_checks.sh
  modules/L30_routersploit.sh
  modules/L99_cleanup.sh
  modules/P60_deep_extractor.sh
Labels: enhancement, System emulator (Lxx)

#644 use env variable CONTAINER to choose the docker container
  installer.sh
  installer/I05_emba_docker_image_dl.sh
  installer/helpers.sh
Labels: enhancement, Installation

#660 JNAP unauth check
  modules/L10_system_emulation.sh
  modules/L22_upnp_hnap_checks.sh
  modules/L25_web_checks.sh
Labels: enhancement, System emulator (Lxx)

#668 Update workflows
  .github/workflows/default_install.yml
  .github/workflows/docker-image.yml
  .github/workflows/shellcheck.yml
Labels: bug, ci/cd

#669 Adjust workflows / CWE checker update to v0.7
  .github/workflows/default_install.yml
  installer/I02_UEFI_fwhunt.sh
  installer/I120_cwe_checker.sh
Labels: bug, Core modules (Sxx), ci/cd

#677 s22 tear down functionality
  modules/S22_php_check.sh
Labels: enhancement, Core modules (Sxx)
