Repository e-m-b-a/emba, pull requests merged in 2023-03, with the labels that each got.

#502 return if empty
  helpers/helpers_emba_parameter_parser.sh
  helpers/helpers_emba_print.sh
Labels: bug, EMBArk

#505 Input validation
  helpers/helpers_emba_parameter_parser.sh
  helpers/helpers_emba_print.sh
  installer/ID1_ubuntu_os.sh
Labels: EMBArk

#504 Check for update setting
  installer/ID1_ubuntu_os.sh
Labels: enhancement, EMBArk, Installation

#503 Routersploit update workflow
  .github/workflows/routersploit_update.yml
  config/routersploit_cve-db.txt
  config/routersploit_exploit-db.txt
  helpers/routersploit_db_update.sh
Labels: enhancement, ci/cd

#515 System emulation improvements, workflow
  .github/workflows/default_install.yml
  .github/workflows/shellcheck.yml
  check_project.sh
  emba
  helpers/helpers_emba_helpers.sh
  helpers/helpers_emba_print.sh
  helpers/helpers_emba_system_emulation.sh
  helpers/routersploit_db_update.sh
  installer.sh
  installer/IF20_cve_search.sh
  installer/helpers.sh
  modules/F20_vul_aggregator.sh
  modules/L10_system_emulation.sh
  modules/L10_system_emulation/network.sh
  modules/L15_emulated_checks_nmap.sh
  modules/L35_metasploit_check.sh
  modules/P70_unblob.sh
Labels: bug, enhancement, Installation, System emulator (Lxx), Core modules (Sxx), ci/cd

#518 CVE state message printing
  check_project.sh
  helpers/helpers_emba_defaults.sh
  helpers/helpers_emba_dependency_check.sh
  helpers/helpers_emba_helpers.sh
  modules/L10_system_emulation/inferService.sh
  modules/P70_unblob.sh
  modules/S17_apk_check.sh
Labels: enhancement, cve-search

#529 Input adjustment
  check_project.sh
  emba
  helpers/helpers_emba_parameter_parser.sh
  helpers/helpers_emba_print.sh
Labels: EMBArk

#530 version validation
  helpers/helpers_emba_print.sh
Labels: bug, EMBArk

#531 PATH variable bug
  emba
Labels: bug

#543 L10 module improvements
  helpers/fix_bins_lnk_emulation.sh
  modules/L10_system_emulation.sh
  modules/P70_unblob.sh
  modules/S115_usermode_emulator.sh
Labels: enhancement, System emulator (Lxx)

#549 New version strings (Flex and NBTscan)
  config/bin_version_strings.cfg
Labels: enhancement, Core modules (Sxx)

#550 L10 improvement round x
  config/trickest_blacklist.txt
  helpers/fix_bins_lnk_emulation.sh
  modules/L10_system_emulation.sh
  modules/L10_system_emulation/network.sh
Labels: bug, enhancement, System emulator (Lxx)

#554 Freetz extraction module deprecated
  modules/P12_avm_freetz_ng_extract.sh
Labels: enhancement

#553 fix for #551
  modules/F50_base_aggregator.sh
  modules/S12_binary_protection.sh
Labels: bug
