Repository e-m-b-a/emba, pull requests merged in 2024-05, with the labels that each got.

#1163 Dhcp version strings and blacklist fix
  config/bin_version_strings.cfg
  modules/S115_usermode_emulator.sh
Labels: enhancement, cve-search, EMBA

#1166 f20 cpe handling #1155
  modules/F20_vul_aggregator.sh
Labels: bug, EMBA

#1168 MODULE_BLACKLIST array handling
  scan-profiles/default-scan-gpt.emba
  scan-profiles/default-scan-no-notify.emba
  scan-profiles/default-scan.emba
  scan-profiles/example-disable-module.emba
  scan-profiles/quick-scan.emba
Labels: bug, EMBA

#1176 improve not on YARA settings
  modules/S110_yara_check.sh
Labels: Core modules (Sxx), EMBA

#1165 F20 CVE version range checking: fix and dead code removal
  modules/F20_vul_aggregator.sh
Labels: bug, cve-search, EMBA

#1177 Less regex / f20 and s21 wording
  config/bin_version_strings.cfg
  modules/F02_toolchain.sh
  modules/S21_python_check.sh
Labels: bug, EMBA

#1178 Update unblob and binwalk installer
  installer/IP61_unblob.sh
  installer/IP99_binwalk_default.sh
Labels: bug, Installation, in progress, EMBA

#1157 System emulation updates
  config/bin_version_strings.cfg
  config/password_regex.cfg
  docker-compose.yml
  helpers/helpers_emba_defaults.sh
  helpers/helpers_emba_dependency_check.sh
  helpers/helpers_emba_parameter_parser.sh
  helpers/helpers_emba_prepare.sh
  installer.sh
  installer/IL10_system_emulator.sh
  installer/IP99_binwalk_default.sh
  modules/F05_qs_resolver.sh
  modules/F20_vul_aggregator.sh
  modules/L10_system_emulation.sh
  modules/L10_system_emulation/fixImage.sh
  modules/L10_system_emulation/inferFile.sh
  modules/L10_system_emulation/inferService.sh
  modules/L10_system_emulation/network.sh
  modules/L10_system_emulation/preInit.sh
  modules/L10_system_emulation/run_service.sh
  modules/L15_emulated_checks_nmap.sh
  modules/L25_web_checks.sh
  modules/S02_UEFI_FwHunt.sh
  modules/S115_usermode_emulator.sh
  modules/S16_ghidra_decompile_checks.sh
  modules/S17_cwe_checker.sh
  modules/S99_grepit.sh
Labels: bug, enhancement, docker, Installation, System emulator (Lxx), Core modules (Sxx), EMBA, Research
